package tests.Adm_Practice;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class UserPropertiesTest2 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void userProperties() throws InterruptedException {
        driver.get("https://qa.hauseheaven.com/");
        driver.manage().window().maximize();
        driver.findElement(By.xpath("//ul[2]/li[2]/a")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("team01");
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("Teamproject1*");
        driver.findElement(By.xpath("//input[@name=\'remember\']")).click();
        driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
        Thread.sleep(1000);
        driver.findElement(By.xpath("//div/div[2]/ul/li[4]/a")).click();
        driver.findElement(By.cssSelector("span > span:nth-child(1)")).click();
        driver.findElement(By.xpath("//input[@id=\'name\']")).click();
        driver.findElement(By.xpath("//input[@id=\'name\']")).sendKeys("Greece");
        js.executeScript("window.scrollTo(0,200)");
        driver.findElement(By.xpath("//textarea[@id=\'description\']")).click();
        driver.findElement(By.xpath("//textarea[@id=\'description\']")).sendKeys("greece");
        {
            WebElement element = driver.findElement(By.xpath("(//button[@type=\'button\'])[4]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("//div[2]/div/p")).click();
        {
            WebElement element = driver.findElement(By.xpath("//div[4]/div/div[2]/div"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-placeholder=\" \">greece</p>'}", element);
        }
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.linkText("Greece")).click();
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).click();
        {
            WebElement element = driver.findElement(By.id("name"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("name")).sendKeys("komsi");
        {
            WebElement element = driver.findElement(By.name("submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.name("submit")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-danger")).click();
        driver.findElement(By.cssSelector(".delete-crud-entry")).click();
        driver.findElement(By.linkText("Logout")).click();
        driver.findElement(By.linkText("Home")).click();
        driver.findElement(By.cssSelector(".ti-arrow-up")).click();
        driver.findElement(By.cssSelector(".image-cover > .container")).click();
    }
}