package tests.Adm_Practice;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.*;

public class UserPropertiesTest01 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void userProperties() throws InterruptedException {
        driver.get("https://qa.hauseheaven.com/");
        driver.manage().window().maximize();

        driver.findElement(By.linkText("Sign In")).click();
        Thread.sleep(1000);
        //driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("team01");
        //driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("Teamproject1*"+Keys.TAB+Keys.ENTER);
        //driver.findElement(By.name("remember")).click();
        //driver.findElement(By.xpath("(//*[@type='submit'])[1]")).click();
        driver.findElement(By.linkText("Properties")).click();
        driver.findElement(By.cssSelector("span > span:nth-child(1)")).click();
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).sendKeys("Greece");
        js.executeScript("window.scrollTo(0,200)");
        driver.findElement(By.id("description")).click();
        driver.findElement(By.id("description")).sendKeys("greece");
        {
            WebElement element = driver.findElement(By.cssSelector(".ck-heading-dropdown > .ck-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".ck-placeholder")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".ck-content"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-placeholder=\" \">greece</p>'}", element);
        }
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.linkText("Greece")).click();
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).click();
        {
            WebElement element = driver.findElement(By.id("name"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("name")).sendKeys("komsi");
        {
            WebElement element = driver.findElement(By.name("submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.name("submit")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-danger")).click();
        driver.findElement(By.cssSelector(".delete-crud-entry")).click();
        driver.findElement(By.linkText("Logout")).click();
        driver.findElement(By.linkText("Home")).click();
        driver.findElement(By.cssSelector(".ti-arrow-up")).click();
        driver.findElement(By.cssSelector(".image-cover > .container")).click();
    }
}
